### ISSUE TITLE
ClientProtocolException NoClassDefFoundError on 0.9.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbufu/openid4java#149]
```
Using the jar for 0.9.6 I am getting a NoClassDefFoundError error when trying 
to create an instance of the ConsumerManager.

I'm using Railo, a cfml engine, to create the object so the errors may not look 
the same as the normal java application.

org/apache/http/client/ClientProtocolException
   at java.net.URLClassLoader$1.run(URLClassLoader.java:217):217
   at java.security.AccessController.doPrivileged(Native Method):-2
   at java.net.URLClassLoader.findClass(URLClassLoader.java:205):205
   at java.lang.ClassLoader.loadClass(ClassLoader.java:321):321
   at java.lang.ClassLoader.loadClass(ClassLoader.java:266):266
   at org.openid4java.consumer.ConsumerManager.<init>(ConsumerManager.java:167):167
   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method):-2
   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57):57
   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45):45
   at java.lang.reflect.Constructor.newInstance(Constructor.java:532):532

To test you can download the express version of railo 
(http://www.getrailo.org/index.cfm/download/) and put this in the webroot's 
index.cfm page along with the jar in the same directory:

<cfset openIDConsumer = createObject('java', 
'org.openid4java.consumer.ConsumerManager', 'openid4java-0.9.6.jar').init() />

<cfdump var="#openIDConsumer#" />

It was working fine with 0.9.5. If you switch between using the 0.9.5 jar and 
0.9.6 jar you will need to restart railo.
```

Original issue reported on code.google.com by `Zoram...@gmail.com` on 20 Apr 2011 at 10:25
