### ISSUE TITLE
xalan version problems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbufu/openid4java#46]
```
What steps will reproduce the problem?
1. replace xalan2.6.0 with 2.7.0 or 2.7.1
2. log in with open id url
3. consumer servlet breaks.

What is the expected output? What do you see instead?
missing classes

What version of the product are you using? On what operating system?


Please provide any additional information below.
Is there any particular reason why openxri is dependent on xalan 2.6? I'm
running into a number of missing class issues trying to get it openId4java
to work with 2.7 and above.

eg.

java.lang.NoClassDefFoundError: org/apache/xpath/compiler/FuncLoader
    org.openxri.xml.XRD.<clinit>(XRD.java:108)
    org.openid4java.discovery.Discovery.<init>(Discovery.java:59)
    org.openid4java.consumer.ConsumerManager.<init>(ConsumerManager.java:51)


```

Original issue reported on code.google.com by `matts...@gmail.com` on 13 Jan 2008 at 10:17
